server:
  port: 9001

logging:
  level:
    pl.office.storage: DEBUG

storage:
  directory: C:\upload
  encrypted: false
  id: 1
  instance-type: MAIN
  server-host: localhost
  server-port: ${server.port}

storage-manager:
  url: http://localhost:9002
  register: /api/storage/register
  register-rate: 10000

